title: Aka.ms/yourpc - Your smartphone on your PC
description: Get notice of calls, messages, notifications,etc and receive , reply and attend all with this great innovation till now .Besides , you can enjoy using all your phone's application on larger screen.
